### ISSUE TITLE
link /sbin/ldconfig to /sbin/ldconfig.real

### ISSUE THREAD

**Issue by antsh415** [zocker-160/handbrake-nvenc-docker#3]
May I ask you that add a symbolic link : 

ln -s /sbin/ldconfig/ /sbin/ldconfig.real

as part of the docker file? On Ubuntu/Debian systems they actually need ldconfig.real to exist for acceleration to work. For me, the nvidia acceleration doesn't work until i perform the above command, but after it is all good. I don't know they details about why this is the case, but from looking around debian based systems use ldconfig.real for some reason. I would make my own docker file and fork it, but I have no idea how. Right now I am manually running the above command when the image updates.

**Comment by zocker-160** [comment]
this is weird and the first time I hear about this, I personally have tested both Ubuntu and Debian and it did work for me without any changes, but after looking into the container I found out that `/sbin/ldconfig.real` is actually missing for some reason.

Thanks for the hint, I will update the image.

**Comment by zocker-160** [comment]
I just pushed an update to `zocker160/handbrake-nvenc:testing`, could you @antsh415 test and confirm that it works for you?

**Comment by stalinCCCP415** [comment]
Hmm, I get the below now:

Status: Downloaded newer image for zocker160/handbrake-nvenc:testing
Creating handbrake ... error

ERROR: for handbrake  Cannot start service handbrake: OCI runtime create failed: container_linux.go:349: starting container process caused "process_linux.go:449: container init caused \"process_linux.go:432: running prestart hook 1 caused \\\"error running hook: exit status 1, stdout: , stderr: nvidia-container-cli: ldcache error: process /sbin/ldconfig.real failed with error code: 1\\\\n\\\"\"": unknown

ERROR: for handbrake  Cannot start service handbrake: OCI runtime create failed: container_linux.go:349: starting container process caused "process_linux.go:449: container init caused \"process_linux.go:432: running prestart hook 1 caused \\\"error running hook: exit status 1, stdout: , stderr: nvidia-container-cli: ldcache error: process /sbin/ldconfig.real failed with error code: 1\\\\n\\\"\"": unknown
ERROR: Encountered errors while bringing up the project.

**Comment by zocker-160** [comment]
this is very strange, I sadly cannot reproduce the issue at all
I am starting the container up with this command:
`docker run --gpus all -p 5801:5800 zocker160/handbrake-nvenc:testing`

Are you sure you have the Nvidia driver and `nvidia-docker2` properly installed?
(the official guide from Nvidia can be found [here](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/install-guide.html#installing-on-ubuntu-and-debian))

does `sudo docker run --rm --gpus all nvidia/cuda:11.0-base nvidia-smi` work for you?

**Comment by stalinCCCP415** [comment]
Thanks for taking a look. Yes to both.

I have other containers (plex and folding at home, for example) working fine with nvidia acceleration. 

The other interesting thing is if I take the :latest image, go into bash inside the container and run the link command I show above, and restart the container, everything starts working.

**Comment by zocker-160** [comment]
I don't know how I could fix it for you, since the `:testing` image is nothing else than the `:latest` with `RUN ln -s /sbin/ldconfig/ /sbin/ldconfig.real` added..... :/

**Comment by stalinCCCP415** [comment]
Hmm, maybe it's an order of operations thing? I'm not savvy enough to look at the code. Could you somehow try to have that link run as the very last thing before the container is brought up?

The only other thing I can think of is it works the way I do it because the container is brought up once already, and then the link happens, though I don't know how that could affect anything.

**Comment by zocker-160** [comment]
yes it could be a permissions problem, have you done any chmod commands?

all RUN commands in docker are made from root, so that should not be the issue

**Comment by stalinCCCP415** [comment]
I haven't actually. Unfortunately, I can't check what the permissions looks like with the test image either because the container fails to start up.

Thanks for taking a look at this.

This is what the files looks like when I do it manually.

![image](https://user-images.githubusercontent.com/36210008/96493304-aa805c80-11f9-11eb-9ec2-7b7fea266796.png)

**Comment by zocker-160** [comment]
this is inside my `:testing` image right after startup:

![Screenshot_20201019_200329](https://user-images.githubusercontent.com/36563538/96494092-2a341880-1246-11eb-93b5-b0de2a70a2c0.png)

**Comment by zocker-160** [comment]
ok so @stalinCCCP415 I just pushed a new version to `:testing` and I moved the link command to the init script, which gets ran when you start the container up.

so it during runtime instead of buildtime, maybe the could solve the problem

**Comment by stalinCCCP415** [comment]
hmm, still getting the same error, unfortunately.  Maybe it would shine some light on the differences if you take a look at what linuxservier.io is doing with their plex and foldingathome containers since those work out of the box for me?

**Comment by zocker-160** [comment]
Those containers are not comparable, because they need CUDA and thus have the Nvidia library build into the docker container as well.
I did not do that, because that would make the container bigger in size and also it is not needed for NVenc to work.

I will create a new testing image with the cuda library inside, but it should not be needed, since the container does work on all my Debian and Ubuntu based systems and this is also true for most of the users.

**Comment by zocker-160** [comment]
@stalinCCCP415 
ok I just pushed the testing image once again, this time with the cuda library included in the container. 

I did a copy paste from the linuxserver docker image.

**Comment by stalinCCCP415** [comment]
The new testing image doesn't have the link to ldconfig.real so the hardware options don't show up until I do that manually like with the latest image.

One interesting thing I noticed is that in the LSIO images, the sbin folders have ldconfig and ldconfig.real. I guess that is why I wanted you to take a look at them.

**Comment by zocker-160** [comment]
yes I have removed the link, because the linuxserver images don't do that.
Also now I am doing exactly the same like they do, so I don't know why it doesn't work.

**Comment by zocker-160** [comment]
closing stale issue, please reopen when issue still exists or there is useful additional information.
